Update android.yml

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -13,19 +13,19 @@ jobs:
 
     steps:
     - uses: actions/checkout@v4
-    - name: set up JDK 11
+    
+    - name: Set up JDK 11
       uses: actions/setup-java@v4
       with:
         java-version: '11'
         distribution: 'temurin'
         cache: gradle
 
-    - name: Проверка наличия gradlew
-      run: ls -la
-      working-directory: .
+    - name: Verify gradlew presence
+      run: test -f gradlew || { echo "gradlew not found"; exit 1; }
 
-    - name: Предоставить права на выполнение для gradlew
+    - name: Grant execute permission for gradlew
       run: chmod +x ./gradlew
 
-    - name: Сборка с помощью Gradle
+    - name: Build with Gradle
       run: ./gradlew build
